### ISSUE TITLE
Add setup.py and handle dependecies correctly

### ISSUE THREAD

**Issue by kerel-fs** [glidernet/ogn-python#16]
Currently, we install developer-tools in production (coveralls, pep8, etc.).
To fix that, we should introduce a `setup.py` which defines the general dependencies.
The dev-tools remain in `requirements.txt`, the other dependencies are installed by
`-e .` in `requirements.txt`.

see also https://caremad.io/2013/07/setup-vs-requirement/

**Comment by Turbo87** [comment]
nice link @kerel-fs! looks like skylines is actually doing it mostly correct too :)
