### ISSUE TITLE
Change travis and coveralls to glidernet

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-python#3]
For the travis-ci.org and coveralls.io badges in the README.md the repository and account from Meisterschueler is used.

Glidernet has to activate the "glidernet/ogn-python" branch in travis-ci.org and coveralls.io

**Comment by kerel-fs** [comment]
Activated travis&coveralls for glidernet/ogn-python yesterday, renamed URLs in badges in my branch feature/+tests, didn't create a PullRequest (feel free to fetch&push to glidernet/ogn-python).
