### ISSUE TITLE
ogn.parser: flarm hardware version has hexadecimal value

### ISSUE THREAD

**Issue by kerel-fs** [glidernet/ogn-python#44]
The flarm hardware version is represented by two hexadecimal, not decimal, digits.
There are already packets in the wild with version-strings `0C` and `0A`.

**Comment by Meisterschueler** [comment]
The field "hardware version" is a "small integer" (uint8). Should we change the parser so it convert the hexadecimal to decimal? Or should we change the field "hardware version" to string(2) ?

**Comment by kerel-fs** [comment]
We should change the parser to parse the hexadecimal string into a python-integer and add a database-migration to corect all previous values. This way, its consistent with the software_version (also number type, float) and with the [ruby-implementation](https://github.com/svoop/ogn_client-ruby/blob/master/lib/ogn_client/messages/sender.rb#L122).

**Comment by kerel-fs** [comment]
Fixed by #45, fix merged with #46.
