### ISSUE TITLE
Enhance parser

### ISSUE THREAD

**Issue by Meisterschueler** [glidernet/ogn-python#48]
These messages fail:
`Annecy>SAR,TCPIP*,qAC,GLIDERN1:;ICA3836BC*120606h4558.98N/00610.66E'205/110/A=004441 !W31! +040fpm +0.0rot 13.8dB 0e +6.0kHz gps1x2`
`LFLE>SAR,TCPIP*,qAC,GLIDERN2:;ICA3836BC*144310h4533.60N/00558.48E'234/009/A=000948 !W02! -019fpm -0.1rot 35.0dB 0e +5.9kHz gps1x2`
`OGNFFFABF>APRS,RELAY*,qAS,Moosburg:/172316h4827.52N/01155.87Ez266/000/A=001417 !W55! id03FFFABF +000fpm +0.0rot`

**Comment by snip** [comment]
This is still beta messages .. not sure if the format will be kept the same.

**Comment by wbuczak** [comment]
Hi

The first two are not aircraft beacons but receiver beacons I guess ?

Cheers
Wojtek

On 24 February 2016 at 08:20, Sebastien Chaumontet <notifications@github.com

**Comment by pjalocha** [comment]
These are the responses to a SAR request, I am considering this method of quickly locating a lost aircraft and I try to keep it along the APRS specification. The new code 0.2.5 responds to such requests. The feature is new and still subject to discussion.

Pawel.

**Comment by kerel-fs** [comment]
The parser moved into a separated repository [glidernet/python-ogn-client](https://github.com/glidernet/python-ogn-client), issue moved to glidernet/python-ogn-client#1.
