### ISSUE TITLE
python2 support

### ISSUE THREAD

**Issue by kerel-fs** [glidernet/ogn-python#6]
Should we support python2?
Your latest change broke python2 support (e.g. there is no BrokenPipeError in 2.7),
we should at least specify the supported python versions.

**Comment by Meisterschueler** [comment]
I use python 3 and I see no drawbacks if we dont support python 2. But I have no problem if someone makes it python 2 compatible...
What would "BrokenPipeError" be in 2.7?

**Comment by kerel-fs** [comment]
I agree with you and don't see any benefits of python2 support since all major distributions support python3.
