### ISSUE TITLE
Wide Exceptions lose errors

### ISSUE THREAD

**Issue by matburnham** [glidernet/ogn-python#62]
In trying to get ogn-python going I commented out a wide exception handler in `ogn/gateway/process_tools.py` (see 8078f806fde02d2d92fc49aa8afe0a25b5ba4c40).

This highlighted a number of AircraftBeacon fields causing exceptions. This meant that these beacons were being ignored (and possibly other beacons being processed in the same batch and also rolled back).

Apart from maybe a top-level exception handler so that the process doesn't stop completely, these ought not to be catching errors and hiding bugs.

**Comment by Meisterschueler** [comment]
With 1866bd9 the integrity errors should be history
