### ISSUE TITLE
trouble with installation and setup - step 5

### ISSUE THREAD

**Issue by GliderGeek** [glidernet/ogn-python#70]
thanks for creating this. i am unfortunately having some trouble setting this up. i am very new to backend programming, so it might be stupid mistakes from my side. it would be great if you could help me out.

os: Mac OS 10.14.4

step 5 says: `./flask database init`.
- This only (partly) worked when executing the following command inside the `ogn_python` folder (with the `app.py`): `flask database init` (without `./`). I am not sure if this is correct?
- It throws the following `RuntimeError`: 
```
RuntimeError: The environment variable 'OGN_CONFIG_MODULE' is not set and as such configuration could not be loaded.  Set this variable and make it point to a configuration file
```

**Comment by Meisterschueler** [comment]
Hi, just set the environment variable:
`export OGN_CONFIG_MODULE='config/default.py'`
I will write it into the documentation and then close this ticket.

**Comment by GliderGeek** [comment]
i think i actually tried this, will report when im home and can test again

**Comment by GliderGeek** [comment]
@Meisterschueler: regarding `./flask` vs `flask`: is this a difference between mac and linux?

**Comment by GliderGeek** [comment]
Ive added the environment variable and now get the following error:
```
  File "/Users/matthijs/github/ogn-python/env/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 453, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/matthijs/github/ogn-python/env/lib/python3.7/site-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  role "ogn" does not exist

(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by GliderGeek** [comment]
another trivial issue i encountered was with the paths in step 11:
```
flask database import_airports ../tests/SeeYou.cup
```

instead of:
```
flask database import_airports tests/SeeYou.cup
```

**Comment by GliderGeek** [comment]
i have completed all the steps 👍

**Comment by GliderGeek** [comment]
found another type: `last_minutes` instead of `minutes`
